# .goreleaser.yaml
version: 2
project_name: tailscale-derper

before:
  hooks:
    - go mod tidy
    - git submodule update --init --recursive

builds:
  - id: xdpderper
    env:
      - CGO_ENABLED=0
      - TS_USE_GOCROSS=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/xdpderper
    binary: xdpderper
    dir: tailscale

  - id: derper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/derper
    binary: derper
    dir: tailscale

nfpms:
  - package_name: tailscale-derper
    homepage: https://tailscale.com
    maintainer: Lee Briggs <mail@lbrlabs.com>
    description: Tailscale DERP and XDPDERP servers
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    contents:
      - src: xdpderper.service
        dst: /usr/lib/systemd/system/xdpderper.service
      - src: derper.service
        dst: /usr/lib/systemd/system/derper.service
    scripts:
      preinstall: ./scripts/preinstall.sh
      postinstall: ./scripts/postinstall.sh

archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

checksum:
  name_template: 'checksums.txt'


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: lbrlabs
    name: derper-package
